### ISSUE TITLE
write 2-3 user stories

### ISSUE THREAD

**Issue by fchikwekwe** [fchikwekwe/FaceSpace#5]

**Comment by StephanieCherubin** [comment]
- [ ] Update wiki: https://github.com/fchikwekwe/FaceSpace/wiki

**Comment by fchikwekwe** [comment]
WIP : https://docs.google.com/document/d/1v1B4Gf8fTLAxLSwZtnuqddWkrnEPL-8z74Y-H6S7Iqk/edit#
